# Group Project I

1. Introduction
2. Replication of data tests

In [32]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib

ImportError: No module named 'seaborn'

In [22]:
dataframe = pd.read_excel("Bishayee Colony Counts 10.27.97-3.8.01.xlsx", na_values = [' '], header = 0, skiprows = [1,2], parse_cols = ("D:F"))

In [27]:
data = dataframe.dropna(axis = 0)

In [28]:

data = data.as_matrix()

data.sort(axis = 1) #sort the columns based on the values to get min, median and max

fenzi = data[:,1] - data[:,0]
fenmu = data[:,2] - data[:,0]
fenzi = np.delete(fenzi, (715), axis = 0)
fenmu = np.delete(fenmu, (715), axis = 0)

mid_ratio = fenzi / fenmu

In [29]:
for i in range(len(fenmu)): ## This is to determine the zeros...
    if fenmu[i] == 0:
        u = i

In [31]:
data[714,:] # Denote that the 714th row of the values are all eqaul, so not possible to calculate mid_ratio

array([ 2.,  2.,  2.])

In [ ]:
fenzi = np.delete(fenzi, (u), axis = 0)
fenmu = np.delete(fenmu, (u), axis = 0)



In [10]:
numpy_hist = plt.figure() # This is to get the histogram
plt.hist(mid_ratio, bins = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

(array([  27.,   70.,   88.,  114.,  375.,  410.,  125.,   67.,   60.]),
 array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9]),
 <a list of 9 Patch objects>)

In [15]:
mid_ratio

array([0.8666666666666667, 1.0, 0.21428571428571427, ...,
       0.3684210526315789, 0.4375, 0.5882352941176471], dtype=object)