# Group Project I

1. Introduction
2. Replication of data tests

In [126]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib

Using matplotlib backend: MacOSX


In [127]:
dataframe = pd.read_excel("Bishayee Colony Counts 10.27.97-3.8.01.xlsx", header = 0, skiprows = [1,2], parse_cols = ("D:F"))

In [154]:
data = dataframe.as_matrix()
data[19, 2] = 110
data.sort(axis = 1) #sort the columns based on the values to get min, median and max

fenzi = data[:,1] - data[:,0]
fenmu = data[:,2] - data[:,0]
fenzi = np.delete(fenzi, (715), axis = 0)
fenmu = np.delete(fenmu, (715), axis = 0)

mid_ratio = fenzi / fenmu

In [ ]:
for i in range(len(fenmu)): ## This is to determine the zeros...
    if fenmu[i] == 0:
        u = i

In [ ]:
fenzi = np.delete(fenzi, (u), axis = 0)
fenmu = np.delete(fenmu, (u), axis = 0)



In [157]:
numpy_hist = plt.figure() # This is to get the histogram
plt.hist(mid_ratio, bins = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0])

(array([  70.,   88.,  114.,  375.,  410.,  125.,   67.,   54.,   31.]),
 array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ]),
 <a list of 9 Patch objects>)

In [159]:
a = np.array([1,2,3,4,5,0,0,6,7,8])


In [160]:
a

array([1, 2, 3, 4, 5, 0, 0, 6, 7, 8])